In [1]:
import pandas as pd
import numpy as np

In [ ]:
'''
from gensim.models import KeyedVectors

# load the pre-trained GloVe model
glove_model = KeyedVectors.load_word2vec_format("glove.6B/glove.6B.300d.txt", binary=False)

# define the text
text = "The quick brown fox jumps over the lazy dog."

# tokenize the text
tokens = nltk.word_tokenize(text)

# produce the text embeddings
text_embeddings = [glove_model[token] for token in tokens if token in glove_model.vocab]

print(text_embeddings)
# Output: a list of 300-dimensional vectors representing each token in the text
'''

In [ ]:
#pip install gensim -q
!pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable


In [7]:
import numpy as np

import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_datasets as tfds

import matplotlib.pyplot as plt

print("Version: ", tf.__version__)
print("Eager mode: ", tf.executing_eagerly())
print("Hub version: ", hub.__version__)
print("GPU is", "available" if tf.config.list_physical_devices('GPU') else "NOT AVAILABLE")


ImportError: libtiff.so.5: cannot open shared object file: No such file or directory

In [4]:
! pip install tensorflow-gpu -q

In [2]:
train_data, test_data = tfds.load(name="imdb_reviews", split=["train", "test"], 
                                  batch_size=-1, as_supervised=True)

train_examples, train_labels = tfds.as_numpy(train_data)
test_examples, test_labels = tfds.as_numpy(test_data)


2023-01-23 21:18:28.046545: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [5]:
test_data = pd.read_csv('test.csv')
train_data = pd.read_csv('train.csv')
train_data = train_data.dropna()
train_data = train_data.drop_duplicates(subset = ["abstract"], keep = 'first')

# Create a list of the categories to remove
categories_to_remove = ["q-alg", "funct-an", "alg-geom"]

# Get the indices of the rows that contain the categories to remove
indices_to_remove = train_data[train_data["category"].isin(categories_to_remove)].index

# Remove the rows at the specified indices
train_data = train_data.drop(indices_to_remove)

In [6]:
train_data['category'].value_counts()

cs          139252
math        105162
cond-mat     42786
physics      38243
astro-ph     38059
stat         22747
quant-ph     16021
eess         15847
hep-ph       11420
hep-th       10695
gr-qc         8663
q-bio         5665
hep-ex        3955
math-ph       3823
nucl-th       3521
q-fin         3053
nlin          2894
econ          2050
nucl-ex       1792
hep-lat       1136
Name: category, dtype: int64

In [7]:

train_examples = train_data['abstract']
train_labels = train_data['category']
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder().fit(train_labels)
train_labels = label_encoder.transform(train_labels)


test_examples = test_data['abstract']
test_labels = label_encoder.transform(test_data['category'])

In [8]:
print("Training entries: {}, test entries: {}".format(len(train_examples), len(test_examples)))


Training entries: 476784, test entries: 43785


In [9]:
train_examples[:10]


/tmp/ipykernel_21788/2625206427.py:1: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  train_examples[:10]


0      Dense crowd counting is a challenging task t...
1      Normalizing flows are a class of probabilist...
2      This work is a continuation of our previous ...
3      In the early 1960s, P. Malliavin and L. A. R...
4      We study the positional game where two playe...
5      We study the dynamics of an initially flat i...
6      In this paper we explore the richness of inf...
7      We investigate the effect of surface acousti...
8      This article addresses persistent tangles. T...
9      We will characterize topological conjugacy c...
Name: abstract, dtype: object

In [10]:
train_labels[:10]

array([ 2,  2, 10, 10, 10, 15,  2, 15, 10, 10])

In [11]:
model = "https://tfhub.dev/google/nnlm-en-dim50/2"
hub_layer = hub.KerasLayer(model, input_shape = [], dtype = tf.string, trainable = True)
hub_layer(train_examples[:3])

/tmp/ipykernel_21788/2396709687.py:3: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  hub_layer(train_examples[:3])


<tf.Tensor: shape=(3, 50), dtype=float32, numpy=
array([[ 0.809098  ,  0.1168115 ,  0.29250333,  0.2892169 , -0.37243056,
         0.02060221, -0.06440666,  0.34763062, -0.6728331 , -0.13544196,
        -0.43448693,  0.36766475, -0.05640075, -0.54886657,  0.05164126,
        -0.26764873, -0.0297319 , -0.3271354 ,  0.2447519 , -0.32231644,
        -0.2930313 , -0.03544194,  0.35894462, -0.35640982, -0.05050799,
         0.27518833, -0.38704887,  0.25569925,  0.00976736, -0.5562808 ,
         0.01999548, -0.06102654,  0.13713919, -0.50512695, -0.359764  ,
        -0.2889675 ,  0.23885444, -0.50300163,  0.2572857 , -0.4060746 ,
        -0.04605572,  0.23608406, -0.23477592,  0.27607197, -0.06051204,
        -0.3060291 ,  0.1176362 , -0.1106792 ,  0.31977695,  0.26576367],
       [ 0.59189564, -0.24073584,  0.18992148,  0.05803103, -0.5346191 ,
        -0.27446163, -0.10460155,  0.73914963, -0.53678477,  0.03414432,
        -0.594916  ,  0.12759608, -0.16587828, -0.4807253 ,  0.20173442,
 

In [12]:
hub_layer(train_examples[:3]).shape

/tmp/ipykernel_21788/3096230664.py:1: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  hub_layer(train_examples[:3]).shape


TensorShape([3, 50])

In [13]:
model = tf.keras.Sequential()
model.add(hub_layer)
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(1))

model.summary()


Instructions for updating:
Lambda fuctions will be no more assumed to be used in the statement where they are used, or at least in the same block. https://github.com/tensorflow/tensorflow/issues/56089


Instructions for updating:
Lambda fuctions will be no more assumed to be used in the statement where they are used, or at least in the same block. https://github.com/tensorflow/tensorflow/issues/56089


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 keras_layer (KerasLayer)    (None, 50)                48190600  
                                                                 
 dense (Dense)               (None, 16)                816       
                                                                 
 dense_1 (Dense)             (None, 1)                 17        
                                                                 
Total params: 48,191,433
Trainable params: 48,191,433
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.compile(optimizer='adam',
              loss=tf.losses.CategoricalCrossentropy(from_logits=True),
              metrics=[tf.metrics.BinaryAccuracy(threshold=0.0, name='accuracy')])


In [15]:
x_val = train_examples[:10000]
partial_x_train = train_examples[10000:]

y_val = train_labels[:10000]
partial_y_train = train_labels[10000:]


/tmp/ipykernel_21788/1971615408.py:1: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  x_val = train_examples[:10000]
/tmp/ipykernel_21788/1971615408.py:2: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  partial_x_train = train_examples[10000:]


In [ ]:
history = model.fit(partial_x_train,
                    partial_y_train,
                    epochs=40,
                    batch_size=512,
                    validation_data=(x_val, y_val),
                    verbose=1)

Epoch 1/40
505/912 [===============>..............] - ETA: 7:08 - loss: 0.0000e+00 - accuracy: 0.0896

In [ ]:
results = model.evaluate(test_examples, test_labels)

print(results)

In [ ]:
history_dict = history.history
history_dict.keys()

In [ ]:
acc = history_dict['accuracy']
val_acc = history_dict['val_accuracy']
loss = history_dict['loss']
val_loss = history_dict['val_loss']

epochs = range(1, len(acc) + 1)

# "bo" is for "blue dot"
plt.plot(epochs, loss, 'bo', label='Training loss')
# b is for "solid blue line"
plt.plot(epochs, val_loss, 'b', label='Validation loss')
plt.title('Training and validation loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

plt.show()

In [7]:
import numpy as np
import tensorflow as tf
import tensorflow_hub as hub
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Load the train and test data
train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')

# Clean the train data
train_data = train_data.dropna()
train_data = train_data.drop_duplicates(subset=["abstract"], keep='first')
categories_to_remove = ["q-alg", "funct-an", "alg-geom"]
indices_to_remove = train_data[train_data["category"].isin(categories_to_remove)].index
train_data = train_data.drop(indices_to_remove)

# Prepare the train and test examples and labels
train_examples = train_data['abstract']
train_labels = train_data['category']
label_encoder = LabelEncoder().fit(train_labels)
train_labels = label_encoder.transform(train_labels)
test_examples = test_data['abstract']
test_labels = label_encoder.transform(test_data['category'])

from tensorflow.keras.utils import to_categorical

train_labels = to_categorical(train_labels, num_classes=20)
test_labels = to_categorical(test_labels, num_classes=20)

'''
# Load the pre-trained model
model = "https://tfhub.dev/google/nnlm-en-dim50/2"
hub_layer = hub.KerasLayer(model, input_shape=[], dtype=tf.string, trainable=True)

# Build the model
model = tf.keras.Sequential()
model.add(hub_layer)
model.add(tf.keras.layers.Dense(128, activation='relu'))
model.add(tf.keras.layers.Dropout(0.5))
model.add(tf.keras.layers.Dense(128, activation='relu'))
model.add(tf.keras.layers.Dropout(0.5))
model.add(tf.keras.layers.Dense(64, activation='relu'))
model.add(tf.keras.layers.Dropout(0.5))
model.add(tf.keras.layers.Dense(64, activation='relu'))
model.add(tf.keras.layers.Dropout(0.5))
model.add(tf.keras.layers.Dense(20, activation='softmax'))
'''
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_addons as tfa
#import tensorflow_text
tfhub_handle_encoder = "https://tfhub.dev/tensorflow/bert_multi_cased_L-12_H-768_A-12/4"
tfhub_handle_preprocess = "https://tfhub.dev/tensorflow/bert_multi_cased_preprocess/3"
DROPOUT_RATE = 0.1
NUM_CLASSES = 20

def build_classifier_model():
    text_input = tf.keras.layers.Input(shape=(), dtype=tf.string, name="text")
    preprocessing_layer = hub.KerasLayer(tfhub_handle_preprocess, name="preprocessing")
    encoder_inputs = preprocessing_layer(text_input)
    encoder = hub.KerasLayer(tfhub_handle_encoder, trainable=True, name="BERT_encoder")
    outputs = encoder(encoder_inputs)
    net = outputs["pooled_output"]
    net = tf.keras.layers.Dropout(DROPOUT_RATE)(net)
    net = tfa.layers.InstanceNormalization()(net)
    net = tf.keras.layers.Dense(NUM_CLASSES, activation='softmax', name="classifier")(net)
    return tf.keras.Model(text_input, net)

model = build_classifier_model()


# Compile the model
model.compile(optimizer='adam', loss=tf.losses.CategoricalCrossentropy(), metrics=['accuracy'])

# Train the model
history = model.fit(train_examples, train_labels, epochs=10, batch_size=512, validation_data=(test_examples, test_labels), verbose=1)


FileNotFoundError: Op type not registered 'RegexSplitWithOffsets' in binary running on limsim-inspiron5584. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
 You may be trying to load on a different device from the computational device. Consider setting the `experimental_io_device` option in `tf.saved_model.LoadOptions` to the io_device such as '/job:localhost'.

In [5]:
pip install tensorflow_text

Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.8/5.8 MB 1.9 MB/s eta 0:00:00m eta 0:00:010:01:010m
Note: you may need to restart the kernel to use updated packages.
